/** This file is overwritten by the CI build system to generate the correct info at build time
 * Any artifact with the values below was not generated by the builder and is considered a DEVELOPER build.
 */

#ifndef H_BUILD_H
#define H_BUILD_H

// Replaced by use of syscfg.yml
#define BUILD_TARGET_NAME_REPLACED_BY_BUILD "toto"
#define BUILD_DATE_REPLACED_BY_BUILD "01/01/1970"
#define BUILD_VERSION_MAJOR_REPLACED_BY_BUILD 0
#define BUILD_VERSION_MINOR_REPLACED_BY_BUILD 0
#define BUILD_VERSION_DEVNUMBER_REPLACED_BY_BUILD 0

#endif  /* H_BUILD_H */
